---

- include: install_additional_packages.yml
  tags: packages

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml
  tags: virtualenv

- include: setup_ssh_keys.yml
  tags: virtualenv

- include: setup_git_repo.yml

- include: setup_django_app.yml

- include: setup_frontend_app.yml

- include: setup_supervisor.yml
  tags: supervisor

- include: set_file_permissions.yml

- include: setup_nginx.yml
