---

- name: Install forever to manage node servers
  npm: name=forever global=yes

- name: Install frontend app dependencies
  command: npm install
  args:
    chdir: "{{ project_path }}"
  # notify: restart nginx

# It would be best if forever would run as a service
- name: Stop node render server if is running
  command: forever stop render_server.js
  ignore_errors: yes
  args:
    chdir: "{{ project_path }}"
  tags:
    - deploy

- name: Start node render server is running
  command: forever start render_server.js
  args:
    chdir: "{{ project_path }}"
  tags:
    - deploy