---

- name: Install Nginx
  apt: name=nginx update_cache={{ update_apt_cache }} state=installed
  tags: packages

- name: Copy the SSL certificate to the remote server
  copy: content={{ ssl_crt }} dest={{ ssl_dest_dir }}/{{ application_name }}.crt
  tags: ssl

- name: Copy the SSL private key to the remote server
  copy: content={{ ssl_key }} dest={{ ssl_dest_dir }}/{{ application_name }}.key
  tags: ssl

# TODO: Fix this, we want to be able to put password via prompt each time
# or do ssh agent forwarding which didn't seem to work, at least with vagrant
- name: Copy script for ssl key decryption
  copy:
    src: "../scripts/decrypt_ssh_key.py"
    dest: "/tmp/decrypt_ssh_key.py"
    mode: 0744
  tags: ssl

- name: Decrypt ssl key
  command: python /tmp/decrypt_ssh_key.py {{ ssl_dest_dir }}/{{ application_name }}.key "{{ ssl_pass }}"
  tags: ssl

- name: Create the Nginx configuration file
  template: src={{ application_name }}.j2
            dest=/etc/nginx/sites-available/{{ application_name }}
            backup=yes
  notify: restart nginx
  tags: nginx.configure

- name: Ensure that the default site is disabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: Ensure that the application site is enabled
  file: src=/etc/nginx/sites-available/{{ application_name }}
        dest=/etc/nginx/sites-enabled/{{ application_name }}
        state=link
  notify: reload nginx

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes
