---

- name: restart application
  supervisorctl: name={{ application_name }} state=restarted

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart render server
  command: forever restart render_server.js
  args:
    chdir: "{{ project_path }}"

- name: pull
  command: git pull
  args:
    chdir: "{{ project_path }}"
  tags: git.pull