---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  become: yes
  become_user: root
  # remote_user: root
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
    - postgresql_dev_headers: yes
    - postgresql_contrib: yes
    - postgresql_postgis: yes
    - postgresql_listen_addresses:
        - '*'
    - postgresql_authentication:
      - type: host
        user: all
        database: all
        address: '0.0.0.0/0'
        method: trust

  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml
  roles:
    - base
    - db
    - rabbitmq
    - web
    - celery
