---

- name: Provision a {{ application_name }} web server
  hosts: webservers
  become: yes
  become_user: root
  remote_user: root
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml
  vars_prompt:
    - name: "ssh_pass"
      prompt: "Enter your SSH password"
      private: yes
  roles:
    - base
    - web
    - nginx
